; ============================================================
;  ClaimsFlow Scan Agent — NSIS Installer
;  Requires NSIS 3.x + MUI2
;
;  Build inputs (must exist before running makensis):
;    dist\claimsflow-scan-agent.exe   (built by pkg — embeds agent + drivers + welcome page)
;    winsw.exe                        (downloaded from github.com/winsw/winsw)
;    winsw.xml                        (service descriptor)
;    assets\wizard-sidebar.bmp        (164×314 — generated by scripts\generate-installer-assets.js)
;    assets\icon.ico                  (optional — falls back to NSIS default)
; ============================================================

!include "MUI2.nsh"
!include "x64.nsh"
!include "LogicLib.nsh"
!include "WinVer.nsh"

; ── Metadata ─────────────────────────────────────────────────────────────────
!define PRODUCT_NAME      "ClaimsFlow Scan Agent"
!define PRODUCT_VERSION   "1.3.0"
!define PRODUCT_PUBLISHER "CIC Insurance Group PLC"
!define PRODUCT_URL       "https://claimsflow-frontend.onrender.com"
!define SERVICE_ID        "ClaimsFlowScanAgent"
!define AGENT_PORT        "7420"
!define REG_KEY           "Software\ClaimsFlow\ScanAgent"
!define UNINST_KEY        "Software\Microsoft\Windows\CurrentVersion\Uninstall\ClaimsFlowScanAgent"

Name          "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile       "ClaimsFlow-Scan-Agent-Setup.exe"
InstallDir    "$PROGRAMFILES64\${PRODUCT_NAME}"
InstallDirRegKey HKLM "${REG_KEY}" "InstallDir"
RequestExecutionLevel admin
Unicode True
SetCompressor /SOLID lzma

; ── Modern branded wizard appearance ──────────────────────────────────────────
!define MUI_ABORTWARNING
; Custom assets are optional — guard each so makensis compiles with or without
; them (generate-installer-assets.js produces them in the normal build).
!if /FileExists "assets\icon.ico"
  !define MUI_ICON   "assets\icon.ico"
  !define MUI_UNICON "assets\icon.ico"
!endif
!if /FileExists "assets\wizard-sidebar.bmp"
  ; Branded left panel on Welcome + Finish pages (164×314 BMP).
  !define MUI_WELCOMEFINISHPAGE_BITMAP   "assets\wizard-sidebar.bmp"
  !define MUI_UNWELCOMEFINISHPAGE_BITMAP "assets\wizard-sidebar.bmp"
  !define MUI_WELCOMEFINISHPAGE_BITMAP_NOSTRETCH
!endif

!define MUI_WELCOMEPAGE_TITLE   "Welcome to ${PRODUCT_NAME} Setup"
!define MUI_WELCOMEPAGE_TEXT    "This wizard installs the ClaimsFlow Scan Agent — your bridge between any office scanner and the ClaimsFlow web app.$\r$\n$\r$\nThe agent runs as a background Windows service on port ${AGENT_PORT} and connects ClaimsFlow to TWAIN, WIA, ISIS, eSCL and network scanners — Canon, Kodak Alaris, Fujitsu, Epson, HP, Brother, Xerox and more.$\r$\n$\r$\nClick Next to continue."
!define MUI_FINISHPAGE_TEXT     "The ClaimsFlow Scan Agent is installed and running.$\r$\n$\r$\nA premium setup & driver console is now available at http://127.0.0.1:${AGENT_PORT}/ — open it to detect scanners and install official vendor drivers."
!define MUI_FINISHPAGE_RUN              ""
!define MUI_FINISHPAGE_RUN_TEXT         "Open the Scan Agent console"
!define MUI_FINISHPAGE_RUN_FUNCTION     "LaunchConsole"
!define MUI_FINISHPAGE_LINK             "Open ClaimsFlow in your browser"
!define MUI_FINISHPAGE_LINK_LOCATION    "${PRODUCT_URL}"

; ── Pages ──────────────────────────────────────────────────────────────────────
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

; ── Version info ─────────────────────────────────────────────────────────────
VIProductVersion "1.3.0.0"
VIAddVersionKey "ProductName"     "${PRODUCT_NAME}"
VIAddVersionKey "ProductVersion"  "${PRODUCT_VERSION}"
VIAddVersionKey "CompanyName"     "${PRODUCT_PUBLISHER}"
VIAddVersionKey "FileDescription" "ClaimsFlow Local Scan Agent Installer"
VIAddVersionKey "FileVersion"     "${PRODUCT_VERSION}"
VIAddVersionKey "LegalCopyright"  "© 2026 ${PRODUCT_PUBLISHER}"

; ══════════════════════════════════════════════════════════════════════════════
;  Init — detect an existing install and offer Repair / Reinstall / Uninstall
; ══════════════════════════════════════════════════════════════════════════════
Var PrevVersion

Function .onInit
  ${IfNot} ${AtLeastWin10}
    MessageBox MB_ICONSTOP "ClaimsFlow Scan Agent requires Windows 10 or later."
    Abort
  ${EndIf}

  ReadRegStr $PrevVersion HKLM "${UNINST_KEY}" "DisplayVersion"
  ${If} $PrevVersion != ""
    MessageBox MB_YESNOCANCEL|MB_ICONQUESTION \
      "ClaimsFlow Scan Agent $PrevVersion is already installed.$\r$\n$\r$\nYes  = Repair / reinstall (this version ${PRODUCT_VERSION})$\r$\nNo   = Remove the existing version first, then install$\r$\nCancel = Exit" \
      IDYES continue IDNO uninstall_first
    Abort               ; Cancel
    uninstall_first:
      ReadRegStr $0 HKLM "${UNINST_KEY}" "UninstallString"
      ${If} $0 != ""
        ExecWait '$0 /S _?=$INSTDIR'   ; run old uninstaller, wait
      ${EndIf}
    continue:
  ${EndIf}
FunctionEnd

Function LaunchConsole
  ExecShell "open" "http://127.0.0.1:${AGENT_PORT}/"
FunctionEnd

; ══════════════════════════════════════════════════════════════════════════════
;  Install sections
; ══════════════════════════════════════════════════════════════════════════════
Section "ClaimsFlow Scan Agent (required)" SecMain
  SectionIn RO  ; cannot be deselected

  ; Stop + remove any previous service before overwriting files (repair path)
  nsExec::ExecToStack 'sc stop "${SERVICE_ID}"'
  Pop $0
  Sleep 2000
  nsExec::ExecToStack '"$INSTDIR\winsw.exe" uninstall'
  Pop $0

  SetOutPath "$INSTDIR"
  SetOverwrite on

  ; ── Core files ──────────────────────────────────────────────────────────────
  File "dist\claimsflow-scan-agent.exe"
  File "winsw.exe"
  File "winsw.xml"

  ; Keep a copy of the setup so Apps & Features → Modify can repair/reinstall
  ; without re-downloading. $EXEPATH is the running installer.
  CopyFiles /SILENT "$EXEPATH" "$INSTDIR\maintenance.exe"

  ; Web console artwork — read at runtime from beside the exe (swappable without
  ; rebuilding). icon.ico is always generated; hero/logo are optional.
  SetOutPath "$INSTDIR\assets"
  File "assets\icon.ico"
  File /nonfatal "assets\hero.webp"
  File /nonfatal "assets\logo.png"
  File /nonfatal "assets\logo.webp"
  SetOutPath "$INSTDIR"

  CreateDirectory "$INSTDIR\logs"

  ; ── Install + start Windows service ─────────────────────────────────────────
  nsExec::ExecToStack '"$INSTDIR\winsw.exe" install "$INSTDIR\winsw.xml"'
  Pop $0
  ${If} $0 != 0
    MessageBox MB_ICONEXCLAMATION "Service installation failed (code $0).$\r$\nThe agent was installed but will not start automatically.$\r$\nYou can start it manually from: $INSTDIR\claimsflow-scan-agent.exe"
  ${Else}
    nsExec::ExecToStack 'sc start "${SERVICE_ID}"'
    Pop $0
  ${EndIf}

  ; ── Start Menu ───────────────────────────────────────────────────────────────
  CreateDirectory "$SMPROGRAMS\ClaimsFlow"
  CreateShortcut  "$SMPROGRAMS\ClaimsFlow\Scan Agent Console.lnk" \
                  "http://127.0.0.1:${AGENT_PORT}/"
  CreateShortcut  "$SMPROGRAMS\ClaimsFlow\Uninstall Scan Agent.lnk" \
                  "$INSTDIR\Uninstall.exe"

  ; ── Registry ─────────────────────────────────────────────────────────────────
  WriteRegStr   HKLM "${REG_KEY}" "InstallDir" "$INSTDIR"
  WriteRegStr   HKLM "${REG_KEY}" "Version"    "${PRODUCT_VERSION}"
  WriteRegStr   HKLM "${REG_KEY}" "Port"       "${AGENT_PORT}"

  WriteRegStr   HKLM "${UNINST_KEY}" "DisplayName"          "${PRODUCT_NAME}"
  WriteRegStr   HKLM "${UNINST_KEY}" "DisplayIcon"          "$INSTDIR\claimsflow-scan-agent.exe"
  WriteRegStr   HKLM "${UNINST_KEY}" "UninstallString"      '"$INSTDIR\Uninstall.exe"'
  WriteRegStr   HKLM "${UNINST_KEY}" "QuietUninstallString" '"$INSTDIR\Uninstall.exe" /S'
  ; "Modify" in Apps & Features re-runs the bundled maintenance installer, which
  ; lets the user Repair / Reinstall at any time after first install.
  WriteRegStr   HKLM "${UNINST_KEY}" "ModifyPath"           '"$INSTDIR\maintenance.exe"'
  WriteRegStr   HKLM "${UNINST_KEY}" "InstallLocation"      "$INSTDIR"
  WriteRegStr   HKLM "${UNINST_KEY}" "Publisher"            "${PRODUCT_PUBLISHER}"
  WriteRegStr   HKLM "${UNINST_KEY}" "URLInfoAbout"         "${PRODUCT_URL}"
  WriteRegStr   HKLM "${UNINST_KEY}" "DisplayVersion"       "${PRODUCT_VERSION}"
  WriteRegDWORD HKLM "${UNINST_KEY}" "NoModify"             0
  WriteRegDWORD HKLM "${UNINST_KEY}" "NoRepair"             1
  ; Estimated size (KB) for Apps & Features
  WriteRegDWORD HKLM "${UNINST_KEY}" "EstimatedSize"        51200

  WriteUninstaller "$INSTDIR\Uninstall.exe"
SectionEnd

; ── Optional: redistributable driver bridges (NAPS2 + Mopria) via winget ───────
Section "Driver bridges: NAPS2 + Mopria (recommended)" SecBridges
  ; These are the freely-redistributable bridges that make every TWAIN/ISIS and
  ; network scanner reachable through a standard interface. Installed from the
  ; official sources via winget; skipped silently if winget is unavailable.
  nsExec::ExecToStack 'winget --version'
  Pop $0
  ${If} $0 == 0
    DetailPrint "Installing NAPS2 (TWAIN/ISIS bridge) via winget…"
    nsExec::ExecToLog 'winget install --id cyanfish.NAPS2 --exact --silent --accept-package-agreements --accept-source-agreements --disable-interactivity'
    Pop $0
    DetailPrint "Installing Mopria Scan (driverless network scanning) via winget…"
    nsExec::ExecToLog 'winget install --id Mopria.ScanService --exact --silent --accept-package-agreements --accept-source-agreements --disable-interactivity'
    Pop $0
  ${Else}
    DetailPrint "winget not found — skipping driver bridges. Install them later from the Scan Agent console."
  ${EndIf}
SectionEnd

; ── Optional: desktop shortcut ─────────────────────────────────────────────────
Section "Desktop shortcut" SecDesktop
  CreateShortcut "$DESKTOP\ClaimsFlow Scan Agent.lnk" "http://127.0.0.1:${AGENT_PORT}/"
SectionEnd

; ── Component descriptions ─────────────────────────────────────────────────────
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SecMain}    "The Scan Agent service and its premium setup console. Required."
  !insertmacro MUI_DESCRIPTION_TEXT ${SecBridges} "NAPS2 (TWAIN/ISIS) and Mopria (driverless network scanning). Free, open, and let the agent reach Canon, Kodak, Fujitsu, Epson, HP and more."
  !insertmacro MUI_DESCRIPTION_TEXT ${SecDesktop} "Add a desktop shortcut to the Scan Agent console."
!insertmacro MUI_FUNCTION_DESCRIPTION_END

; ══════════════════════════════════════════════════════════════════════════════
;  Uninstall
; ══════════════════════════════════════════════════════════════════════════════
Section "Uninstall"
  nsExec::ExecToStack 'sc stop "${SERVICE_ID}"'
  Pop $0
  Sleep 2000
  nsExec::ExecToStack '"$INSTDIR\winsw.exe" uninstall'
  Pop $0
  Sleep 1000

  Delete "$INSTDIR\claimsflow-scan-agent.exe"
  Delete "$INSTDIR\winsw.exe"
  Delete "$INSTDIR\winsw.xml"
  Delete "$INSTDIR\maintenance.exe"
  Delete "$INSTDIR\Uninstall.exe"
  RMDir  /r "$INSTDIR\logs"
  RMDir  /r "$INSTDIR\assets"
  RMDir  "$INSTDIR"

  Delete "$SMPROGRAMS\ClaimsFlow\Scan Agent Console.lnk"
  Delete "$SMPROGRAMS\ClaimsFlow\Uninstall Scan Agent.lnk"
  RMDir  "$SMPROGRAMS\ClaimsFlow"
  Delete "$DESKTOP\ClaimsFlow Scan Agent.lnk"

  DeleteRegKey HKLM "${REG_KEY}"
  DeleteRegKey HKLM "${UNINST_KEY}"
SectionEnd
