; ============================================================
;  ClaimsFlow Scan Agent — Inno Setup 6 Installer
;  Build:  iscc installer.iss  (from build-windows.ps1)
;
;  Prerequisites:
;    dist\claimsflow-scan-agent.exe   (built by @yao-pkg/pkg)
;    winsw.exe                        (WinSW v3 service wrapper)
;    winsw.xml                        (service config)
;    assets\wizard-sidebar.bmp        (164×314  — generated by scripts\generate-installer-assets.js)
;    assets\wizard-header.bmp         (497×58   — generated)
; ============================================================

#define AppName      "ClaimsFlow Scan Agent"
#define AppVersion   "1.3.0"
#define AppPublisher "CIC Insurance Group PLC"
#define AppURL       "https://claimsflow-frontend.onrender.com"
#define AppExeName   "claimsflow-scan-agent.exe"
#define ServiceID    "ClaimsFlowScanAgent"
#define AgentPort    "7420"

[Setup]
AppId                    ={{A7B3C2D1-E4F5-6789-ABCD-EF0123456789}
AppName                  ={#AppName}
AppVersion               ={#AppVersion}
AppVerName               ={#AppName} {#AppVersion}
AppPublisher             ={#AppPublisher}
AppPublisherURL          ={#AppURL}
AppSupportURL            ={#AppURL}
AppUpdatesURL            ={#AppURL}
DefaultDirName           ={autopf}\ClaimsFlow Scan Agent
DefaultGroupName         =ClaimsFlow
DisableProgramGroupPage  =yes
OutputBaseFilename       =ClaimsFlow-Scan-Agent-Setup
OutputDir                =.
Compression              =lzma2/ultra64
SolidCompression         =yes
InternalCompressLevel    =ultra64
ArchitecturesInstallIn64BitMode=x64compatible
; Re-running this installer over an existing install enters Inno's built-in
; maintenance mode (Modify / Repair / Remove) automatically via AppId.
#if FileExists("assets\icon.ico")
SetupIconFile            =assets\icon.ico
#endif

; ── Modern wizard appearance ──────────────────────────────────────────────────
WizardStyle              =modern
WizardSizePercent        =120
WizardResizable          =no
; Sidebar image: dark branded panel on the left (164×314 BMP)
WizardImageFile          =assets\wizard-sidebar.bmp
WizardImageStretch       =yes
; Small header icon used on inner pages (55×55 BMP)
WizardSmallImageFile     =assets\wizard-header.bmp

; ── Privilege + execution ────────────────────────────────────────────────────
PrivilegesRequired       =admin
PrivilegesRequiredOverridesAllowed=dialog
CloseApplications        =yes
RestartApplications      =no

; ── Version metadata (shows in file properties) ──────────────────────────────
VersionInfoVersion       ={#AppVersion}.0
VersionInfoCompany       ={#AppPublisher}
VersionInfoDescription   =ClaimsFlow Local Scan Agent Installer
VersionInfoProductName   ={#AppName}
VersionInfoProductVersion={#AppVersion}
VersionInfoCopyright     =© 2026 {#AppPublisher}

; ── Uninstall ────────────────────────────────────────────────────────────────
UninstallDisplayName     ={#AppName}
UninstallDisplayIcon     ={app}\{#AppExeName}
CreateUninstallRegKey    =yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[CustomMessages]
english.WelcomeLabel1  =Welcome to ClaimsFlow Scan Agent Setup
english.WelcomeLabel2  =%nThis installer will set up the ClaimsFlow Scan Agent {#AppVersion} on your computer.%n%nThe agent runs as a Windows service on port {#AgentPort} and connects ClaimsFlow to any TWAIN, ISIS, WIA, or eSCL-compatible scanner — including Canon, Kodak Alaris, Fujitsu, Epson, HP, and Xerox devices.%n%nClick Next to continue.
english.FinishedLabel  =ClaimsFlow Scan Agent {#AppVersion} has been installed and started as a Windows service.%n%nA premium setup & driver console is now available at http://127.0.0.1:{#AgentPort}/ — open it to detect scanners and install official vendor drivers.%n%nPort: {#AgentPort} · Diagnostics: http://127.0.0.1:{#AgentPort}/diagnostics

[Tasks]
Name: "autostart";   Description: "Start the agent automatically with Windows (recommended)"; GroupDescription: "Service options:"; Flags: checked
Name: "naps2";       Description: "Download and install NAPS2 for TWAIN/ISIS support (Canon, Kodak, Fujitsu)"; GroupDescription: "Optional components:"
Name: "desktopicon"; Description: "Create a desktop shortcut for the Scan Agent console"; GroupDescription: "Shortcuts:"

[Files]
; Core agent executable
Source: "dist\{#AppExeName}"; DestDir: "{app}"; Flags: ignoreversion

; WinSW service wrapper + config
Source: "winsw.exe";    DestDir: "{app}"; DestName: "winsw.exe";    Flags: ignoreversion
Source: "winsw.xml";    DestDir: "{app}"; DestName: "winsw.xml";    Flags: ignoreversion

; Driver modules (loaded at runtime from ./drivers/)
Source: "drivers\*"; DestDir: "{app}\drivers"; Flags: ignoreversion recursesubdirs

; Web console artwork — read at runtime from {app}\assets (swappable)
Source: "assets\icon.ico";  DestDir: "{app}\assets"; Flags: ignoreversion
Source: "assets\hero.webp"; DestDir: "{app}\assets"; Flags: ignoreversion skipifsourcedoesntexist
Source: "assets\logo.png";  DestDir: "{app}\assets"; Flags: ignoreversion skipifsourcedoesntexist

; License / readme
Source: "README.md"; DestDir: "{app}"; Flags: ignoreversion isreadme

[Dirs]
Name: "{app}\logs"

[Icons]
; Start Menu
Name: "{group}\ClaimsFlow Scan Agent Console"; Filename: "http://127.0.0.1:{#AgentPort}/"
Name: "{group}\Diagnostics (browser)";     Filename: "http://127.0.0.1:{#AgentPort}/diagnostics"
Name: "{group}\Uninstall Scan Agent";      Filename: "{uninstallexe}"

; Desktop shortcut (optional task)
Name: "{commondesktop}\ClaimsFlow Scan Agent"; Filename: "{app}\{#AppExeName}"; WorkingDir: "{app}"; Tasks: desktopicon

[Registry]
Root: HKLM; Subkey: "Software\ClaimsFlow\ScanAgent"; ValueType: string;  ValueName: "InstallDir"; ValueData: "{app}";             Flags: uninsdeletekey
Root: HKLM; Subkey: "Software\ClaimsFlow\ScanAgent"; ValueType: string;  ValueName: "Version";    ValueData: "{#AppVersion}"
Root: HKLM; Subkey: "Software\ClaimsFlow\ScanAgent"; ValueType: string;  ValueName: "Port";       ValueData: "{#AgentPort}"

[Run]
; Install + start Windows service
Filename: "{app}\winsw.exe"; Parameters: "install ""{app}\winsw.xml"""; StatusMsg: "Installing Windows service…"; Flags: runhidden waituntilterminated
Filename: "net";             Parameters: "start {#ServiceID}";           StatusMsg: "Starting ClaimsFlow Scan Agent service…"; Flags: runhidden waituntilterminated; Tasks: autostart

; Download NAPS2 (optional task)
Filename: "winget"; Parameters: "install --id cyanfish.naps2 --silent --accept-source-agreements --accept-package-agreements"; StatusMsg: "Installing NAPS2 (TWAIN/ISIS driver)…"; Flags: runhidden waituntilterminated shellexec; Tasks: naps2

; Open diagnostics page after install
Filename: "{#AppURL}"; Description: "Open ClaimsFlow in browser"; Flags: postinstall shellexec skipifsilent

[UninstallRun]
; Stop + remove service on uninstall
Filename: "net";         Parameters: "stop {#ServiceID}"; Flags: runhidden waituntilterminated; RunOnceId: "StopService"
Filename: "{app}\winsw.exe"; Parameters: "uninstall ""{app}\winsw.xml"""; Flags: runhidden waituntilterminated; RunOnceId: "RemoveService"

[UninstallDelete]
Type: filesandordirs; Name: "{app}\logs"
Type: dirifempty;     Name: "{app}"

[Code]
// ── Pre-install checks ───────────────────────────────────────────────────────

function IsServiceRunning(ServiceName: string): Boolean;
var
  ResultCode: Integer;
begin
  Exec('sc.exe', 'query ' + ServiceName, '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  Result := (ResultCode = 0);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then begin
    // Stop existing service before overwriting files
    if IsServiceRunning('{#ServiceID}') then begin
      Exec('net.exe', 'stop {#ServiceID}', '', SW_HIDE, ewWaitUntilTerminated, WizardForm.Tag);
      Sleep(2000);
    end;
    // Attempt to uninstall previous winsw registration
    Exec(ExpandConstant('{app}\winsw.exe'), 'uninstall', ExpandConstant('{app}'), SW_HIDE, ewWaitUntilTerminated, WizardForm.Tag);
    Sleep(1000);
  end;
end;

function InitializeSetup(): Boolean;
var
  Version: TWindowsVersion;
begin
  GetWindowsVersionEx(Version);
  // Require Windows 10 or later (WIA 2.0, modern TWAIN support)
  if Version.Major < 10 then begin
    MsgBox('ClaimsFlow Scan Agent requires Windows 10 or later.'#13#10'Please upgrade your operating system.', mbError, MB_OK);
    Result := False;
  end else
    Result := True;
end;

// ── Installer page customisation ─────────────────────────────────────────────
// Applies the dark color scheme to wizard form elements at runtime.

procedure InitializeWizard();
begin
  // Dark background for the inner wizard area
  WizardForm.Color                 := $00110A05;   // BGR: #050A11 (dark navy)
  WizardForm.MainPanel.Color       := $001A1005;
  WizardForm.InnerPage.Color       := $001A1005;

  // Text colours
  WizardForm.WelcomeLabel1.Font.Color  := $00FFFFFF;
  WizardForm.WelcomeLabel2.Font.Color  := $00C8D4E8;
  WizardForm.FinishedLabel.Font.Color  := $00C8D4E8;
  WizardForm.SelectDirLabel.Font.Color := $00C8D4E8;
  WizardForm.SelectStartMenuFolderLabel.Font.Color := $00C8D4E8;

  // Header
  WizardForm.PageDescriptionLabel.Font.Color := $00A0B4C8;
  WizardForm.PageNameLabel.Font.Color        := $00FFFFFF;
  WizardForm.PageNameLabel.Font.Style        := [fsBold];

  // Button colours (blue-tinted)
  WizardForm.NextButton.Font.Color   := $00FFFFFF;
  WizardForm.BackButton.Font.Color   := $00C8D4E8;
  WizardForm.CancelButton.Font.Color := $00C8D4E8;
end;
