import { Link } from 'react-router-dom'
import { ArrowLeft, ShieldCheck, FileText } from 'lucide-react'
import { Button } from '@/components/ui/button'

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 text-slate-200">
      <header className="border-b border-white/10 bg-slate-950/60 backdrop-blur">
        <div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-3">
            <div className="grid h-9 w-9 place-items-center rounded-lg bg-gradient-to-br from-blue-600 to-indigo-600 shadow-lg shadow-blue-600/20">
              <ShieldCheck className="h-5 w-5 text-white" />
            </div>
            <div>
              <p className="text-sm font-semibold text-white">ClaimsFlow</p>
              <p className="text-xs text-slate-400">CIC Insurance Group PLC</p>
            </div>
          </div>
          <Link to="/register">
            <Button variant="ghost" className="text-slate-300 hover:text-white">
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back
            </Button>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12">
        <div className="mb-8 flex items-center gap-3">
          <FileText className="h-6 w-6 text-blue-400" />
          <h1 className="text-3xl font-bold text-white">Terms of Service</h1>
        </div>
        <p className="mb-10 text-sm text-slate-400">
          Effective date: 23 April 2026 &middot; Last updated: 23 April 2026
        </p>

        <section className="space-y-10 text-[15px] leading-relaxed text-slate-300">
          <Block title="1. Introduction">
            <p>
              These Terms of Service (the &ldquo;<strong>Terms</strong>&rdquo;) govern your access
              to and use of the ClaimsFlow platform (the &ldquo;<strong>Platform</strong>&rdquo;),
              a claims intake, workflow, adjudication and audit system operated by
              <strong> CIC Insurance Group PLC</strong>, a public company incorporated in the
              Republic of Kenya under Company Number [TODO: registration number], with its
              registered office at [TODO: registered office address] (&ldquo;<strong>CIC</strong>
              &rdquo;, &ldquo;<strong>we</strong>&rdquo;, &ldquo;<strong>our</strong>&rdquo;, or
              &ldquo;<strong>us</strong>&rdquo;). By creating an account, logging in, or otherwise
              accessing the Platform you agree to be legally bound by these Terms. If you do not
              agree, you must not access or use the Platform.
            </p>
          </Block>

          <Block title="2. Definitions">
            <ul className="list-disc space-y-2 pl-6">
              <li>
                <strong>User</strong> means any natural person who accesses the Platform, including
                an employee, officer, contractor or agent of CIC or of a Service Provider.
              </li>
              <li>
                <strong>Service Provider</strong> means a hospital, clinic, garage, assessor,
                broker, agent or other third-party entity registered on the Platform to submit or
                service claims.
              </li>
              <li>
                <strong>Claim</strong> means any medical, motor, property or other insurance
                benefit request lodged on the Platform together with its supporting documents.
              </li>
              <li>
                <strong>Role</strong> means the access profile assigned to a User (including
                Admin, Claims Officer / Maker, Checker, Supervisor, Fraud Officer, Provider Admin
                and Provider User).
              </li>
              <li>
                <strong>Content</strong> means any data, document, image, form, note, message or
                other material submitted to, stored in, or generated by the Platform.
              </li>
            </ul>
          </Block>

          <Block title="3. Eligibility and account registration">
            <p>
              You may use the Platform only if you are at least 18 years old, have the legal
              capacity to enter into a binding contract, and have been duly authorised by CIC or
              by a registered Service Provider. When you register you represent that all
              information you provide is true, accurate and complete, and you undertake to keep
              it current. We reserve the right to verify your identity, employment status,
              professional licences and regulatory standing at any time and to refuse, suspend
              or revoke access on that basis.
            </p>
          </Block>

          <Block title="4. Account security">
            <p>
              You are responsible for safeguarding your credentials (including password and, where
              enabled, two-factor authentication secrets) and for every action taken through your
              account. You must not share your credentials, allow any other person to use your
              account, or access the Platform through any automated means not expressly
              authorised by CIC. You must notify us immediately at [TODO: security@cic.co.ke] if
              you suspect any unauthorised access, lost device, or compromise of your account.
            </p>
          </Block>

          <Block title="5. Role-based access and acceptable use">
            <p>
              Access to features is determined by your Role. You may access, view, edit, approve,
              reject, escalate or export Content only to the extent expressly permitted by your
              Role and only for the legitimate business purpose for which access was granted. You
              must not:
            </p>
            <ul className="list-disc space-y-2 pl-6">
              <li>
                attempt to elevate your privileges, bypass authorisation checks, or access any
                Claim, customer record or workflow queue outside your assigned Role or branch;
              </li>
              <li>
                alter, fabricate, backdate, delete or conceal any Claim, document, audit log or
                workflow entry;
              </li>
              <li>
                introduce malicious code, probe, scan, stress-test or otherwise interfere with
                the integrity, security or availability of the Platform;
              </li>
              <li>
                reverse-engineer, decompile, disassemble, scrape or copy the Platform, its source
                code, database schema or APIs except to the limited extent permitted by
                mandatory law;
              </li>
              <li>
                use the Platform to transmit any content that is unlawful, defamatory, obscene,
                harassing, infringing, or that violates any person&rsquo;s privacy or
                intellectual-property rights.
              </li>
            </ul>
          </Block>

          <Block title="6. Claims accuracy and fraud">
            <p>
              You acknowledge that the Platform is used to adjudicate insurance benefits and that
              false, misleading, exaggerated or fabricated information may constitute insurance
              fraud and an offence under the <em>Insurance Act (Cap. 487)</em>, the{' '}
              <em>Penal Code</em>, the <em>Computer Misuse and Cybercrimes Act, 2018</em> and
              other applicable laws. You undertake to submit only information you believe in good
              faith to be true, to retain supporting originals for the periods required by law,
              and to cooperate fully with any investigation conducted by CIC, the Insurance
              Regulatory Authority, the Directorate of Criminal Investigations or any competent
              authority. CIC may suspend, decline, recover or refer any Claim where fraud is
              reasonably suspected.
            </p>
          </Block>

          <Block title="7. Service Provider obligations">
            <p>
              If you register or operate on the Platform as or on behalf of a Service Provider,
              you additionally represent and warrant that: (a) the Service Provider holds all
              licences, accreditations and tax registrations required by Kenyan law for the
              services it renders; (b) every Claim you lodge reflects services actually rendered
              to an eligible member; (c) you have obtained all necessary consents from the
              member, patient or claimant for the collection, processing and disclosure of their
              personal and, where applicable, health data to CIC via the Platform; and (d) you
              will keep your panel details, bank details and authorised-user list current.
            </p>
          </Block>

          <Block title="8. Documents and uploads">
            <p>
              You retain ownership of Content you upload. By uploading Content you grant CIC a
              worldwide, non-exclusive, royalty-free, sub-licensable licence to host, store,
              reproduce, process, transmit, adjudicate, audit and archive that Content strictly
              for the purposes of operating the Platform, assessing the related Claim, preventing
              fraud, and complying with legal, regulatory and actuarial obligations. You warrant
              that you have the right to grant this licence. You must not upload malware,
              encrypted archives whose keys you will not share, or files unrelated to a Claim.
            </p>
          </Block>

          <Block title="9. Intellectual property">
            <p>
              The Platform, including its software, design, logos, trade marks, workflow
              definitions and documentation, is and remains the exclusive property of CIC and its
              licensors. Nothing in these Terms transfers any such rights to you. The name
              &ldquo;ClaimsFlow&rdquo; and the CIC marks may not be used without our prior
              written consent.
            </p>
          </Block>

          <Block title="10. Third-party services">
            <p>
              The Platform may integrate with third-party services (including identity
              verification, SMS, email, payment, cloud storage and document recognition
              providers). Your use of such integrated services may be subject to the third
              party&rsquo;s own terms. CIC is not responsible for the availability, accuracy or
              acts of any third party except to the extent mandatory law provides otherwise.
            </p>
          </Block>

          <Block title="11. Availability; no warranty">
            <p>
              The Platform is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo;
              basis. To the maximum extent permitted by law, CIC disclaims all warranties, express
              or implied, including warranties of merchantability, fitness for a particular
              purpose, non-infringement and uninterrupted or error-free operation. We may
              schedule maintenance, apply patches or throttle abusive traffic at any time.
            </p>
          </Block>

          <Block title="12. Limitation of liability">
            <p>
              To the maximum extent permitted by law, CIC, its affiliates, directors, employees,
              agents and licensors shall not be liable for any indirect, incidental, special,
              consequential, punitive or exemplary damages, or for any loss of profits, revenue,
              data, goodwill or business opportunity, arising out of or in connection with your
              use of the Platform, whether in contract, tort (including negligence), statute or
              otherwise, even if advised of the possibility of such damages. CIC&rsquo;s total
              aggregate liability under these Terms shall not exceed the greater of
              (a) KES 10,000 or (b) the fees actually paid by you to CIC for use of the Platform
              in the twelve (12) months immediately preceding the event giving rise to the
              liability. Nothing in these Terms excludes liability that cannot be excluded under
              Kenyan law, including liability for death or personal injury caused by negligence,
              for fraud, or for wilful misconduct.
            </p>
          </Block>

          <Block title="13. Indemnity">
            <p>
              You will indemnify and hold CIC harmless against any loss, claim, demand, penalty,
              fine or expense (including reasonable legal fees) arising out of: (a) your breach
              of these Terms; (b) your violation of any law or third-party right; (c) any Claim
              you lodge that is fraudulent, exaggerated or unsupported; or (d) any unauthorised
              use of the Platform attributable to your failure to safeguard your credentials.
            </p>
          </Block>

          <Block title="14. Suspension and termination">
            <p>
              We may suspend or terminate your access immediately and without prior notice if we
              reasonably believe that you have breached these Terms, that your continued access
              poses a security or regulatory risk, or that suspension is required by law or by an
              order of a competent authority. Upon termination your right to access the Platform
              ends; Content submitted before termination will be retained in accordance with our
              retention schedule and applicable law.
            </p>
          </Block>

          <Block title="15. Changes to these Terms">
            <p>
              We may update these Terms from time to time. Material changes will be notified to
              you via the Platform or by email at least fourteen (14) days before they take
              effect. Your continued use of the Platform after the effective date constitutes
              acceptance of the revised Terms.
            </p>
          </Block>

          <Block title="16. Governing law and dispute resolution">
            <p>
              These Terms and any dispute or claim arising out of or in connection with them are
              governed by the laws of the Republic of Kenya. The parties shall first attempt in
              good faith to resolve any dispute by negotiation for thirty (30) days. Failing
              resolution, the dispute shall be referred to a single arbitrator appointed in
              accordance with the rules of the Chartered Institute of Arbitrators (Kenya Branch),
              with the seat of arbitration in Nairobi and proceedings in English. Nothing in this
              clause prevents either party from seeking urgent interim or injunctive relief from
              the courts of Kenya.
            </p>
          </Block>

          <Block title="17. Contact">
            <p>
              Questions about these Terms may be sent to{' '}
              <a className="text-blue-400 hover:text-blue-300" href="mailto:legal@cic.co.ke">
                legal@cic.co.ke
              </a>{' '}
              or to the Legal Department, CIC Insurance Group PLC,
              [TODO: registered office address], Nairobi, Kenya.
            </p>
          </Block>
        </section>

        <div className="mt-12 flex items-center justify-between border-t border-white/10 pt-6 text-sm text-slate-400">
          <Link to="/privacy" className="text-blue-400 hover:text-blue-300">
            Read the Privacy Policy &rarr;
          </Link>
          <Link to="/register">
            <Button className="bg-blue-600 hover:bg-blue-500">Back to registration</Button>
          </Link>
        </div>
      </main>
    </div>
  )
}

function Block({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="mb-3 text-lg font-semibold text-white">{title}</h2>
      <div className="space-y-3">{children}</div>
    </div>
  )
}
